package easy

import (
	"fmt"
	"math"
)

func SolveProblem12() {
	/*
		The sequence of triangle numbers is generated by adding the natural
		 numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

		1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

		Let us list the factors of the first seven triangle numbers:

		 1: 1
		 3: 1,3
		 6: 1,2,3,6
		10: 1,2,5,10
		15: 1,3,5,15
		21: 1,3,7,21
		28: 1,2,4,7,14,28
		We can see that 28 is the first triangle number to have over five divisors.

		What is the value of the first triangle number to have over five hundred
		 divisors?
	*/
	ans := getTriangleNumberWithMoreThanNDivisors(500)
	fmt.Printf("Problem 12 Answer: %d\n", ans)
}

func getTriangleNumberWithMoreThanNDivisors(n int) int {
	tri := 1
	index := 1

	minPossible := n * n

	for {
		if tri > minPossible {
			if getNumDivisors(tri) >= n {
				return tri
			}
		}

		index++
		tri += index
	}
}

func getNumDivisors(
	n int,
) int {
	nDivisors := 2 // 1 & n

	max := int(math.Floor(math.Sqrt(float64(n))))
	for i := 2; i <= max; i++ {
		if n%i == 0 {
			if n == max {
				// this number is a square, so the number of
				// divisors only increments once
				nDivisors++
			} else {
				nDivisors += 2
			}
		}
	}

	return nDivisors
}
